#
# Try to find the FreeImagePlus library and include path.
# Once done this will define
#
# FREEIMAGEPLUS_FOUND
# FREEIMAGEPLUS_INCLUDE_PATH
# FREEIMAGEPLUS_LIBRARY
# 

IF (WIN32)
	FIND_PATH( FREEIMAGEPLUS_INCLUDE_PATH FreeImagePlus.h
		${PROJECT_SOURCE_DIR}/extern/FreeImage
        C:/FreeImage/Wrapper/FreeImagePlus/dist/x64
		DOC "The directory where FreeImagePlus.h resides")
	FIND_LIBRARY( FREEIMAGEPLUS_LIBRARY
		NAMES FreeImagePlus freeimageplus
		PATHS
        C:/FreeImage/Wrapper/FreeImagePlus/dist/x64
		${PROJECT_SOURCE_DIR}/FreeImage
		DOC "The FreeImage library")
ELSE (WIN32)
	FIND_PATH( FREEIMAGEPLUS_INCLUDE_PATH FreeImagePlus.h
		/usr/include
		/usr/local/include
		/sw/include
		/opt/local/include
		DOC "The directory where FreeImagePlus.h resides")
	FIND_LIBRARY( FREEIMAGEPLUS_LIBRARY
		NAMES FreeImagePlus freeimageplus
		PATHS
		/usr/lib64
		/usr/lib
		/usr/local/lib64
		/usr/local/lib
		/sw/lib
		/opt/local/lib
		DOC "The FreeImage library")
ENDIF (WIN32)

SET(FREEIMAGEPLUS_LIBRARIES ${FREEIMAGEPLUS_LIBRARY})

IF (FREEIMAGEPLUS_INCLUDE_PATH AND FREEIMAGEPLUS_LIBRARY)
	SET( FREEIMAGEPLUS_FOUND TRUE CACHE BOOL "Set to TRUE if FreeImagePlus is found, FALSE otherwise")
ELSE (FREEIMAGEPLUS_INCLUDE_PATH AND FREEIMAGEPLUS_LIBRARY)
	SET( FREEIMAGEPLUS_FOUND FALSE CACHE BOOL "Set to TRUE if FreeImagePlus is found, FALSE otherwise")
ENDIF (FREEIMAGEPLUS_INCLUDE_PATH AND FREEIMAGEPLUS_LIBRARY)

MARK_AS_ADVANCED(
	FREEIMAGEPLUS_FOUND
	FREEIMAGEPLUS_LIBRARY
	FREEIMAGEPLUS_LIBRARIES
	FREEIMAGEPLUS_INCLUDE_PATH)

IF (FREEIMAGEPLUS_FOUND)
    MESSAGE(STATUS "FREEIMAGEPLUS_INCLUDE_PATH = ${FREEIMAGEPLUS_INCLUDE_PATH}")
    MESSAGE(STATUS "FREEIMAGEPLUS_LIBRARY = ${FREEIMAGEPLUS_LIBRARY}")
ELSE (FREEIMAGEPLUS_FOUND)
    IF (FreeImagePlus_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find FreeImagePlus")
    ENDIF (FreeImagePlus_FIND_REQUIRED)
ENDIF (FREEIMAGEPLUS_FOUND)
