#ifndef THIRTYBITSGCONTEXTPLUGIN_GLOBAL_H
#define THIRTYBITSGCONTEXTPLUGIN_GLOBAL_H

#include <QtGlobal>

#if defined(THIRTYBITSGCONTEXTPLUGIN_LIBRARY)
#  define THIRTYBITSGCONTEXTPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define THIRTYBITSGCONTEXTPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // THIRTYBITSGCONTEXTPLUGIN_GLOBAL_H
